### ISSUE TITLE
Stylistic opinions

### ISSUE THREAD

**Issue by amuradyan** [archavka/List.am#2]
Wonderful job, absolutely love it.

One thing that would have helped me with reading the text, would be better formatting /the headers, paragraphs, bullet points, and such/ though.
I'll try to come up with a version sometime soon.

Keep up the good work.

Best,
A

**Comment by archavka** [comment]
# _List.am-requirments_ 

This is a Requirements Specification document for [List.am](https://list.am).

### Purpose of Document.

[List.am](https://list.am) provides a platform for people to connect around a life stage, a need, a pastime, interest or passion. This document describes it's scope, objectives and goal. In addition to describing non-functional requirements, It also models the functional requirements with use cases.



### Users:

* Unsigned. Guests, can find site navigation, product identification.

* Signed in (be able to access restricted areas of the site through a password protection scheme).
  
  Buyers(can find site navigation, product identification and product ordering) and/or
  Product owners (allowed to maintain the data about their products).


### Responsibilities of platform:

* Provide users access to up-to-date, accurate product information on which they can make a decision to buy.
* Allow differential access to web pages based on type of user.
* Allow users to place their product and maintain information about it.
* Translation of a web page to another languages.


### Functional objectives:

The system shall provide a search facility that will allow full-text searching of all web pages that the user is permitted to access. The system must support
the following searches:
  
  * find all words specified
  * find any word specified
  * find the exact phrase.

The system shall allow user to view the owner of any product and contact him.



### Non-Functional Objectives:

* Reliability
* Usability
* Performance
* Supportability
* Security
* Purchased Components
* Interfaces
