### ISSUE TITLE
How to contribue to this initiative

### ISSUE THREAD

**Issue by oshn** [archavka/List.am#4]
First of all thank you for all good work you do for community.

I as many others also benefit from List.am (thereafter _service_) and would like to see it prosper maintaining quality service. Hence your initiative of supporting the QA of the service is very much on point and I would like to contribute, e.g. sharing ideas via issues. I believe many others are also interested, but maybe hesitate as there's no mention on how to make contributions in compliance with projects current needs. 

If you find it interesting to have more collaborators, consider adding contributing guidelines. Check https://gist.github.com/briandk/3d2e8b3ec8daf5a27a62 as a good example.

**Comment by archavka** [comment]
I would like to thank you ahead for supporting this initiative. There are gaps and compromises in the testing strategy. Contributions are welcome only.  Guideline for contributions is a need.
